
-- Creación de la base de datos
CREATE DATABASE IF NOT EXISTS BBVA;
USE BBVA;

-- Creacion de las tablas
CREATE TABLE CLIENTES(
    C_DNI CHAR(8) PRIMARY KEY,
    C_NOMBRE VARCHAR(30),
    C_APELLIDO VARCHAR(30),
    C_DIRECCION VARCHAR(50),
    C_TELEFONO CHAR(9),
    C_CORREO VARCHAR(100),
    C_ESTADOCIVIL ENUM('soltero', 'casado', 'viudo', 'divorciado')
);

CREATE TABLE CUENTAS(
    CUENTA_ID INT AUTO_INCREMENT PRIMARY KEY,
    C_DNI CHAR(8), 
    FOREIGN KEY (C_DNI) REFERENCES CLIENTES(C_DNI),
    TIPOCUENTA VARCHAR(20),
    FECHACREACION DATE,
    MONTO DECIMAL(10,2),
    MONEDATIPO ENUM('soles', 'dolares')
);

CREATE TABLE SUCURSALES(
    SUCURSAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    SUCURSAL_NOMBRE VARCHAR(50),
    SUCURSAL_DIRECCION VARCHAR(100),
    SUCURSAL_TELEFONO CHAR(9)
);

CREATE TABLE EMPLEADOS(
    E_ID VARCHAR(20) PRIMARY KEY,
    E_CLAVE CHAR(4) UNIQUE,
    E_NOMBRE VARCHAR(30),
    E_APELLIDO VARCHAR(30),
    E_CARGO VARCHAR(25),
    E_SUCURSAL INT,
    FOREIGN KEY (E_SUCURSAL) REFERENCES SUCURSALES(SUCURSAL_ID),
    E_FECHA_CONTRATACION DATE
);

CREATE TABLE TARJETA(
    TARJETA_ID INT PRIMARY KEY,
    CLAVETARJETA CHAR(4) UNIQUE,
    TIPOTARJETA_ID INT,
    TIPOTARJETA_NOMBRE VARCHAR(30),
    TARJETA_ESTADO ENUM('activa', 'bloqueada'),
    TARJETA_MARCA VARCHAR(30)
);

CREATE TABLE TRANSACCIONES(
    TRANSACCION_ID INT AUTO_INCREMENT PRIMARY KEY,
    TRANSACCION_TIPO VARCHAR(30),
    TRANSACCION_FECHA DATE,
    C_DNI CHAR(8),
    FOREIGN KEY (C_DNI) REFERENCES CLIENTES(C_DNI),
    TRANSACCION_MONTO DECIMAL(10,2)
);

CREATE TABLE  CUENTAEVENTO(
    EVENTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHAEVENTO DATE,
    EVENTOTIPO INT,
    MONTO_ANTIGUO DECIMAL(10,2),
    MONTO_NUEVO DECIMAL(10,2),
    Estado_Antiguo ENUM('activa', 'bloqueada'),
    Estado_Nuevo ENUM('activa', 'bloqueada'),
    Autor_Evento VARCHAR(30)
);

CREATE TABLE INTENTOSFALLIDOS(
    INTENTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    TARJETA_ID INT,
    FOREIGN KEY (TARJETA_ID) REFERENCES TARJETA(TARJETA_ID),
    FECHAINTENTO DATE
);


